### ISSUE TITLE
feat: Add send-file argument to binary

### ISSUE THREAD

**Issue by mathew-fleisch** [mathew-fleisch/bashbot#110]
For commands that generate files, it would be nice if bashbot's binary had a native way to send a file to a channel/user like the send-message command/argument

- https://github.com/mathew-fleisch/bashbot/blob/main/cmd/send-message.go
- https://github.com/slack-go/slack/blob/master/files.go
- https://api.slack.com/methods/files.upload

Would enable this idea to work:
https://github.com/mathew-fleisch/bashbot/issues/60

**Comment by wisdommatt** [comment]
@mathew-fleisch If I am clear on this, the commands will:
- Generate the file
- Send the generated file to the slack channel
- Then also delete the file?

**Comment by mathew-fleisch** [comment]
no file generation or deletion/cleanup actually. The feature request would be to just send any target/local file to slack in a specific channel. Maybe also allow it to be sent as a DM too. 

The use case I had in mind, was first captured in [this issue](https://github.com/mathew-fleisch/bashbot/issues/60) to use the [youtube-dl tool](https://itsfoss.com/download-youtube-linux/) to download and rip an mp3 from a youtube video, then post that mp3 as a slack message. A user would trigger it like `!bashbot rip-mp3 https://www.youtube.com/watch?v=dQw4w9WgXcQ` and after downloading and converting, it would use this feature to send the audio in mp3 format back to the user. This would all happen in the bashbot command itself, except for the part where it returns the audio file, which is the missing piece.
