### ISSUE TITLE
Environment variable validation

### ISSUE THREAD

**Issue by mathew-fleisch** [mathew-fleisch/bashbot#58]
Certain commands require additional access, and it would be nice to be able to detect if a command can be run before trying to run it. For example, if an expected environment variable isn't present, the command, when triggered, should error out for missing information. I'm thinking an array of strings representing the expected environment variables (like this but in golang https://github.com/mathew-fleisch/tools/blob/main/scripts/check-environment-variables.sh) at runtime. Just after a valid command is identified, and before it is executed, iterate through the expected environment variables to ensure they are not null/empty. Because there is no validation currently, this is a bug, and a potential enhancement.

**Comment by wisdommatt** [comment]
I would like to work on this as my first issue on the project but i need you to clear somethings to me.

In order to run the command below, the only required environment variable is `SLACK_TOKEN`

`bashbot -config-file bashbot/config.json -send-message-channel bashbot -send-message-text "hello, this is bashbot"`

What i need to create is a `map[string][]string` where the command name e.g `send-message-channel` is the key and the value is `[]string{"SLACK_TOKEN"}`. Whenever the command is run, i should check if all the environment variables are present right ? @mathew-fleisch

**Comment by mathew-fleisch** [comment]
Hey @wisdommatt! Actually, I was referring to when the main bashbot agent is running, not a command like send-message-text. However, you have the right idea of what i'm looking for in functionality.
I'll give an example. When running this command (triggered by running `bashbot aqi #####` from slack, while bashbot is running), there are dependencies that are expected, but not defined, or validated:
https://github.com/mathew-fleisch/bashbot/tree/main/examples/aqi

This [function/command](https://github.com/mathew-fleisch/bashbot/blob/main/examples/aqi/aqi.sh) assumes you have an aqi token saved as an environment variable. It also assumes you have jq and curl installed. If you run bashbot as a container, you can pre-install these dependencies, but if you run bashbot as a go-binary, it will fail, if those things are not present at runtime. I am thinking that there are two new key/value pairs in the configuration json for each function that define the expected environment variables, and other expected tools the script might require. In this case the [command json](https://github.com/mathew-fleisch/bashbot/blob/main/examples/aqi/aqi.json) might change to:
```json
{
  "name": "Air Quality Index",
  "description": "Get air quality index by zip code",
  "envvars": ["AIRQUALITY_API_KEY"],
  "dependencies": ["curl","jq"],
  "help": "bashbot aqi [zip-code]",
  "trigger": "aqi",
  "location": "./examples/aqi",
  "command": [
    "source /bashbot/.env",
    "&& ./aqi.sh ${zip}"
  ],
  "parameters": [
    {
      "name": "zip",
      "allowed": [],
      "description": "any integer between 10000 through 99999",
      "source": ["for i in {10000..99999}; do echo $i; done"]
    }
  ],
  "log": true,
  "ephemeral": false,
  "response": "text",
  "permissions": [
    "all"
  ]
}
```
And there would be two new go functions to validate the expected environment variable is set, and the other dependencies (curl and jq) exist on the host machine before trying to execute the command maybe somewhere around here: https://github.com/mathew-fleisch/bashbot/blob/main/cmd/bashbot/bashbot.go#L329

**Comment by mathew-fleisch** [comment]
When an environment variable is missing, it should throw an error (send a message back to slack) using a new message object, passing the missing env-var(s) back to the user:
https://github.com/mathew-fleisch/bashbot/blob/main/sample-config.json#L43-L45
```json
 {
      "active": true,
      "name": "missingenvvar",
      "text": ":skull_and_crossbones: This command requires this environment variable to be set: [%s]"
}
```

and a similar error message for missing dependencies:
```json
 {
      "active": true,
      "name": "missingdependency",
      "text": ":skull_and_crossbones: This command requires: [%s]"
}
```

**Comment by mathew-fleisch** [comment]
After this functionality exists, I'd also want all of the examples updated to reflect this change as a part of the same PR.

**Comment by wisdommatt** [comment]
@mathew-fleisch i think i now understand what am supposed to do here, thanks for the explanation 💯

**Comment by mathew-fleisch** [comment]
Sweet. Let me know if you have any more questions. You can also raise a PR before you're done, and we can discuss specifics with line-number comments; and I'll wait to merge it until it works properly. Up to you.
