### ISSUE TITLE
Migrate from RTM to new websocket api

### ISSUE THREAD

**Issue by mathew-fleisch** [mathew-fleisch/bashbot#68]
Bashbot was originally created with the [RTM](https://api.slack.com/rtm) api. This is a deprecated/legacy api that has been replaced by the [socket](https://api.slack.com/apis/connections/socket) api. Migrate all RTM functions in Bashbot to use the new api and update read-me to reflect token difference. This will be a "major" change to the semantic version because the "legacy app token" will no longer be necessary to set up Bashbot after this modification. This will also enable bashbot to trigger/listen for reaction/emoji events and button clicks for multi-stage commands.

**Comment by wisdommatt** [comment]
This sounds like an interesting issue, @mathew-fleisch i would like to work on this 🚀 

Is there any other thing i need to know before i proceed ? 🤔

**Comment by mathew-fleisch** [comment]
I haven't done any research on this one other than gathering those two links. If you can sort out what the diff will be, go for it, but I'm not sure what the scope will be. The cool thing this one opens up would be multi-stage commands (button to approve/deny secondary action) as well as triggering commands off of reactions/emojis.

**Comment by wisdommatt** [comment]
Okay, I will do my research on how slack socket API works.

**Comment by wisdommatt** [comment]
@mathew-fleisch I have seen how to work with Slack Socket API, but the problem i am facing now is that it doesn't receive sent messages e.g `bashbot info`.

This is my code below, maybe i am not doing something correctly.

`go

        client := socketmode.New(api)
	go client.Run()
	for event := range client.Events {
		log.Info("event received: ", event.Type)

		switch event.Type {
		case socketmode.EventTypeConnected:
			log.Info("Bashbot ws is now connected to slack. Primary trigger: `" + admin.Trigger + "`")

		case socketmode.EventTypeConnectionError:
			log.Error("Slack socket connection error")
		}
	}
`

**Comment by mathew-fleisch** [comment]
Yea... This is what I was afraid of. The socket mode works very differently than the RTM mode that i'm using currently. I found this [tutorial](https://github.com/xNok/slack-go-demo-socketmode/tree/main) that might help you understand the concept more. However, I do not want to use this guy's fork/handlers and instead write our own. Make sure you have set up the permissions/scopes correctly with your bot user in the slack admin UI so it can read messages and invite the bot user to the channel you're testing in. Most importantly, you must "subscribe" to specific events in the slack admin ui, for the go to pick up on the message event. I [modified your test](https://go.dev/play/p/hQCkL7NrBgH) with information from that tutorial, and am now seeing events from the socket mode... This is super exciting! One of the biggest criticisms I've had of bashbot, is that it relies on this legacy RTM functionality, and this socket mode opens up the possibility of multi-staged commands (like using emoji reactions to approve/deny a command completes based on output). I don't know if I'll want to use all of these event-subscriptions/permissions/scopes, but here is what I have enabled in my own test:

## bot event subscriptions:

- [app_mention](https://api.slack.com/events/app_mention)
- [emoji_changed](https://api.slack.com/events/emoji_changed)
- [member_joined_channel](https://api.slack.com/events/member_joined_channel)
- [message.channels](https://api.slack.com/events/message.channels)
- [message.groups](https://api.slack.com/events/message.groups)
- [message.im](https://api.slack.com/events/message.im)
- [reaction_added](https://api.slack.com/events/reaction_added)
- [reaction_removed](https://api.slack.com/events/reaction_removed)

## scopes

- [app_mentions:read](https://api.slack.com/scopes/app_mentions:read)
- [channels:history](https://api.slack.com/scopes/channels:history)
- [channels:join](https://api.slack.com/scopes/channels:join)
- [channels:read](https://api.slack.com/scopes/channels:read)
- [chat:write](https://api.slack.com/scopes/chat:write)
- [emoji:read](https://api.slack.com/scopes/emoji:read)
- [files:read](https://api.slack.com/scopes/files:read)
- [files:write](https://api.slack.com/scopes/files:write)
- [groups:history](https://api.slack.com/scopes/groups:history)
- [groups:read](https://api.slack.com/scopes/groups:read)
- [groups:write](https://api.slack.com/scopes/groups:write)
- [im:history](https://api.slack.com/scopes/im:history)
- [im:read](https://api.slack.com/scopes/im:read)
- [im:write](https://api.slack.com/scopes/im:write)
- [incoming-webhook](https://api.slack.com/scopes/incoming-webhook)
- [links:read](https://api.slack.com/scopes/links:read)
- [reactions:read](https://api.slack.com/scopes/reactions:read)
- [reactions:write](https://api.slack.com/scopes/reactions:write)
- [users:read](https://api.slack.com/scopes/users:read)
- [workflow.steps:execute](https://api.slack.com/scopes/workflow.steps:execute)


Hope this helps. 😄

**Comment by mathew-fleisch** [comment]
🤦 ok 3 times I've talked about multi-staged commands in this issue. I'll shut up about that now 🤐 🤣

**Comment by wisdommatt** [comment]
@mathew-fleisch thanks, I think this is enough for me to proceed 🤣 

As for the muti-staged commands .... 😆 😆 🤣

**Comment by mathew-fleisch** [comment]
This issue can be closed with this merge
https://github.com/mathew-fleisch/bashbot/pull/73
