### ISSUE TITLE
Documentation on using regex for parameters

### ISSUE THREAD

**Issue by beevelop** [mathew-fleisch/bashbot#94]
In #52 / #62 you introduced the regex feature, which is great for enabling a lot of use cases. Unfortunately, I couldn't find any example of how to configure the parameters with the `match` attribute.

Are there examples / is there any documentation available how to use the regex feature?

**Comment by mathew-fleisch** [comment]
Hey! Thanks for trying out bashbot. I haven't had time to finish the v2 refactor I have been working on. I can post a draft of the read-me for the regex example for now to get you unblocked

...

## Bashbot Example - Regex Command

In this example, a url is validated with a regular expression and curl is used to return the output as a message.

### Bashbot Configuration

This command is triggered by sending `bashbot curl [url]` in a slack channel where Bashbot is also a member. There is no external script for this command, and expects curl to already be installed. Passing a valid url to this curl command will return the http response of that url, using the host system's built-in curl command. Note: Backslashes `\` must be escaped with another backslash. Example: matching a word `\w` would require passing `\\w`

```json
{
  "name": "Curl Example",
  "description": "Pass a valid url to curl",
  "help": "bashbot curl [url]",
  "trigger": "curl",
  "location": "./",
  "command": ["curl -s ${url}"],
  "parameters": [
    {
      "name": "url",
      "allowed": [],
      "description": "A valid url",
      "match": "(http|ftp|https)://([\\w_-]+(?:(?:\\.[\\w_-]+)+))([\\w.,@?^=%&:/~+#-]*[\\w@?^=%&/~+#-])?"
    }
  ],
  "log": false,
  "ephemeral": false,
  "response": "code",
  "permissions": ["all"]
}
```

**Comment by beevelop** [comment]
Thank you @mathew-fleisch that helps a lot. I got it running successfully for the case of parsing a telephone number from Slack (as it is sent as `<tel:+123456789|+123456789>`. To contribute back this is the configuration I came up with for this use case:
```json
        {
          "name": "number1",
          "description": "Number of the participant (format: +123456789)",
          "match": "<tel:\\+[0-9]+\\|\\+[0-9]+>"
        }
```

One side-effect I experienced when using the Regex feature: If I use more than one Regex parameter, it seems as if the first parameter contains the full parameter list and all the following parameters remain empty.

```bash
# Bashbot command: bashbot foo [param1] [param2] [param3]
# Command configured:  "./foo.sh \"${param1}\" \"${param2}\" \"${param3}\""
# All of the parameters are regex parameters

# Triggering the following slack command
bashbot foo value1 value2 value3
# results in
./foo.sh "foo value1 value2 value3" "" "" ""
```

Not sure, if this is down to a misconfiguration on my side, but the behavior seems odd.

**Comment by mathew-fleisch** [comment]
Neat! glad you got it working! I have not tried to use multiple regex params yet, so there is probably just a bug. I'll make sure to fix this before I merge in the v2 changes. Thanks!

**Comment by mathew-fleisch** [comment]
The official v2 documentation has been released. I'd be curious to see how your upgrade/migration goes.
https://github.com/mathew-fleisch/bashbot/tree/main/examples/regex
